# Generated by Django 5.0.1 on 2024-01-15 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('medical_history', models.BooleanField(default=False)),
                ('diet', models.BooleanField(default=False)),
                ('smoker', models.IntegerField()),
                ('height_weight', models.IntegerField()),
                ('patient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient_type')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('consultation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation_status')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialist')),
            ],
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialist_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialist_type'),
        ),
    ]
