# Generated by Django 5.0.1 on 2024-01-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diet',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoker',
            field=models.IntegerField(null=True),
        ),
    ]
